version: '3.8'
services:
  stats-server:
    build: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    restart: always

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    restart: always

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on: 
      - ewm-db
    environment:
        - STATS_SERVER_URL=http://stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=1234
    restart: always

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    restart: always
