CREATE TABLE IF NOT EXISTS statistic
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(7000),
    uri       VARCHAR(1000),
    ip        VARCHAR(1000),
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_statistic PRIMARY KEY (id)
);

