CREATE TABLE IF NOT EXISTS statistic
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(20),
    uri       VARCHAR(1000),
    ip        VARCHAR(1000),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_statistic PRIMARY KEY (id)
);